# n=100;
# m='200'
# print(str(n)+m)
# print(int(m)+n)
# a=input("nhập vào số a: ")
# # print(a)
x=int(input('x: '))
y=int(input('y: '))
print("{0}<{1} là {2}".format(x,y,x<y))
print("{0}>{1} là {2}".format(x,y,x>y))
print("{0}=={1} là {2}".format(x,y,x==y))
print("{0}!={1} là {2}".format(x,y,x!=y))
print("{0}<={1} là {2}".format(x,y,x<=y))
print("{0}>={1} là {2}".format(x,y,x>=y))
print("---------------------------------------")
z=int(input("z: "))
print((x<y) and (y<z))
print((x<y))
